/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   RobotomyRequestForm.cpp                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: akolupae <akolupae@student.hive.fi>        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/04/17 14:10:45 by akolupae          #+#    #+#             */
/*   Updated: 2026/05/08 18:34:18 by akolupae         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "RobotomyRequestForm.hpp"

// Default constructor - should not be used
RobotomyRequestForm::RobotomyRequestForm(void)
: RobotomyRequestForm("DefaultTarget") {}

// Constructor with parameter
RobotomyRequestForm::RobotomyRequestForm(const std::string target)
: AForm("RobotomyRequestForm", 72, 45), _target(target) {

	std::cout << *this << ": RobotomyRequestForm created." << std::endl;
}

// Copy constructor
RobotomyRequestForm::RobotomyRequestForm(const RobotomyRequestForm& other)
: AForm("RobotomyRequestForm", other.getGradeToSign(),
other.getGradeToExecute()), _target(other._target) {}

// Copy assignment operator overload
RobotomyRequestForm&	RobotomyRequestForm::operator=
(const RobotomyRequestForm& other) {

	if (this != &other) {
		this->_target = other._target;
	}

	return (*this);
}

// Destructor
RobotomyRequestForm::~RobotomyRequestForm(void) {
	std::cout << *this << ": RobotomyRequestForm deleted." << std::endl;
}

// Getter
const std::string&	RobotomyRequestForm::getTarget(void) const {
	return (this->_target);
}

// RobotomyRequestForm function
void	RobotomyRequestForm::execute(Bureaucrat const & executor) const {

	try {
		AForm::execute(executor);
	}
	catch (AForm::NotSignedException &e) {
		throw ;
	}
	catch (AForm::GradeTooLowException &e) {
		e.addFormType("RobotomyRequestForm");
		throw ;
	}

	std::cout << "Brrrrrrrrrrrrrrrr...\n";
	if (this->_randomize() == true)
		std::cout << this->_target << " has been robotomized successfully."
			<< std::endl;
	else
		std::cout << "Robotomy failed." << std::endl;
}

/* Randomizing engine
 *
 * std::random_device	a uniformly-distributed integer random number generator
 * 						that produces non-deterministic random numbers;
 *
 * std::mt19937			the Mersenne Twister engine with a popular
 * 						choice of parameters;
 *
 * range(dev())			seeded with random device;
 *
 * dist(0, 1)			transform the random unsigned int generated by range
 * 						into an int in [0, 1].
 */
bool	RobotomyRequestForm::_randomize(void) const {

	static std::random_device	dev;
	static std::mt19937			range(dev());
	static std::uniform_int_distribution<std::mt19937::result_type>	dist(0, 1);

	return (dist(range) % 2 == 1);
}
